=== BulkSecurityGeneratorProjectV2/lutfialquraan__literatum-lutfi/src/main/java/test/dois/JATS-archivearticle1.dtd
<!ELEMENT article (front|body|back)*>
        <!ATTLIST article
                article-type CDATA #REQUIRED
                dtd-version CDATA #REQUIRED
                xml:lang CDATA #REQUIRED
                xmlns:xlink CDATA #REQUIRED>
        <!ELEMENT front (journal-meta|article-meta)*>
        <!ELEMENT journal-meta (journal-id|journal-title-group|issn|publisher)*>
        <!ELEMENT journal-id (#PCDATA)>
        <!ATTLIST journal-id
                journal-id-type CDATA #REQUIRED>
        <!ELEMENT journal-title-group (journal-title)*>
        <!ELEMENT journal-title (#PCDATA)>
        <!ELEMENT issn (#PCDATA)>
        <!ATTLIST issn
                pub-type CDATA #REQUIRED>
        <!ELEMENT publisher (publisher-name|publisher-loc)*>
        <!ELEMENT publisher-name (#PCDATA)>
        <!ELEMENT publisher-loc (#PCDATA)>
        <!ELEMENT article-meta (article-id|article-categories|title-group|contrib-group|aff|author-notes|pub-date|volume|issue|fpage|lpage|permissions|self-uri|abstract|kwd-group)*>
        <!ELEMENT article-id (#PCDATA)>
        <!ATTLIST article-id
                pub-id-type CDATA #REQUIRED>
        <!ELEMENT article-categories (subj-group)*>
        <!ELEMENT subj-group (subject)*>
        <!ATTLIST subj-group
                subj-group-type CDATA #REQUIRED>
        <!ELEMENT subject (#PCDATA)>
        <!ELEMENT title-group (article-title)*>
        <!ELEMENT article-title (#PCDATA)>
        <!ELEMENT contrib-group (contrib|x)*>
        <!ELEMENT contrib (string-name|x|degrees|xref)*>
        <!ATTLIST contrib
                contrib-type CDATA #REQUIRED>
        <!ELEMENT string-name (given-names|surname)*>
        <!ELEMENT given-names (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT degrees (#PCDATA)>
        <!ELEMENT xref (sup|italic)*>
        <!ATTLIST xref
                ref-type CDATA #REQUIRED
                rid CDATA #REQUIRED>
        <!ELEMENT sup (#PCDATA)>
        <!ELEMENT aff (label)*>
        <!ATTLIST aff
                id CDATA #REQUIRED>
        <!ELEMENT label (sup)*>
        <!ELEMENT author-notes (corresp)*>
        <!ELEMENT corresp (email)*>
        <!ATTLIST corresp
                id CDATA #REQUIRED>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT pub-date (month|year)*>
        <!ATTLIST pub-date
                pub-type CDATA #REQUIRED>
        <!ELEMENT month (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT volume (#PCDATA)>
        <!ELEMENT issue (#PCDATA)>
        <!ELEMENT fpage (#PCDATA)>
        <!ELEMENT lpage (#PCDATA)>
        <!ELEMENT permissions (copyright-statement|copyright-year|copyright-holder)*>
        <!ELEMENT copyright-statement (#PCDATA)>
        <!ELEMENT copyright-year (#PCDATA)>
        <!ELEMENT copyright-holder (#PCDATA)>
        <!ATTLIST copyright-holder
                content-type CDATA #REQUIRED>
        <!ELEMENT self-uri (#PCDATA)>
        <!ATTLIST self-uri
                content-type CDATA #REQUIRED
                xlink:href CDATA #REQUIRED>
        <!ELEMENT abstract (p)*>
        <!ELEMENT p (italic|xref|bold)*>
        <!ELEMENT italic (#PCDATA)>
        <!ELEMENT kwd-group (kwd|x)*>
        <!ELEMENT kwd (#PCDATA)>
        <!ELEMENT body (p|sec)*>
        <!ELEMENT sec (title|p|table-wrap|sec|list|fig)*>
        <!ATTLIST sec
                id CDATA #REQUIRED
                sec-type CDATA #IMPLIED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT table-wrap (label|caption|alternatives|table-wrap-foot)*>
        <!ATTLIST table-wrap
                id CDATA #REQUIRED
                position CDATA #REQUIRED>
        <!ELEMENT caption (p)*>
        <!ELEMENT alternatives (graphic|table)*>
        <!ELEMENT graphic (#PCDATA)>
        <!ATTLIST graphic
                xlink:href CDATA #REQUIRED>
        <!ELEMENT table (colgroup|thead|tbody)*>
        <!ELEMENT colgroup (col)*>
        <!ELEMENT col (#PCDATA)>
        <!ATTLIST col
                align CDATA #REQUIRED
                char CDATA #IMPLIED>
        <!ELEMENT thead (tr)*>
        <!ELEMENT tr (th|td)*>
        <!ELEMENT th (#PCDATA)>
        <!ATTLIST th
                align CDATA #REQUIRED>
        <!ELEMENT tbody (tr)*>
        <!ELEMENT td (#PCDATA)>
        <!ATTLIST td
                colspan CDATA #IMPLIED>
        <!ELEMENT list (list-item)*>
        <!ATTLIST list
                id CDATA #REQUIRED
                list-type CDATA #REQUIRED>
        <!ELEMENT list-item (p)*>
        <!ELEMENT bold (#PCDATA)>
        <!ELEMENT table-wrap-foot (fn)*>
        <!ELEMENT fn (p|label)*>
        <!ATTLIST fn
                fn-type CDATA #IMPLIED
                id CDATA #IMPLIED>
        <!ELEMENT fig (label|caption|graphic)*>
        <!ATTLIST fig
                id CDATA #REQUIRED
                position CDATA #REQUIRED>
        <!ELEMENT back (fn-group|ref-list)*>
        <!ELEMENT fn-group (fn)*>
        <!ELEMENT ref-list (title|ref)*>
        <!ELEMENT ref (mixed-citation)*>
        <!ATTLIST ref
                id CDATA #REQUIRED>
        <!ELEMENT mixed-citation (collab|year|source|publisher-loc|publisher-name|person-group|article-title|volume|fpage|lpage|pub-id|edition|ext-link)*>
        <!ATTLIST mixed-citation
                publication-type CDATA #REQUIRED>
        <!ELEMENT collab (#PCDATA)>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT person-group (string-name)*>
        <!ATTLIST person-group
                person-group-type CDATA #REQUIRED>
        <!ELEMENT pub-id (#PCDATA)>
        <!ATTLIST pub-id
                pub-id-type CDATA #REQUIRED>
        <!ELEMENT edition (#PCDATA)>
        <!ELEMENT ext-link (#PCDATA)>
        <!ATTLIST ext-link
                ext-link-type CDATA #REQUIRED
                xlink:href CDATA #REQUIRED>

=== BulkSecurityGeneratorProjectV2/lutfialquraan__literatum-lutfi/contents/192536211700700101.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.1d1 20130915//EN" "JATS-archivearticle1.dtd"><article article-type="letter" dtd-version="1.1d1" xml:lang="en" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink"><front><journal-meta><journal-id journal-id-type="publisher-id">AFPA</journal-id><journal-id journal-id-type="sage">AFP</journal-id><journal-title-group><journal-title>Academic Forensic Pathology</journal-title></journal-title-group><issn pub-type="ppub">1925-3621</issn><issn pub-type="epub">1925-3621</issn><publisher><publisher-name>SAGE Publications</publisher-name><publisher-loc>Sage CA: Los Angeles, CA</publisher-loc></publisher></journal-meta><article-meta><article-id pub-id-type="doi">10.1177/192536211700700101</article-id><article-id pub-id-type="publisher-id">10.1177_192536211700700101</article-id><article-categories><subj-group subj-group-type="heading"><subject>Letter</subject></subj-group></article-categories><title-group><article-title>Letter from the Editor-In-Chief</article-title></title-group><contrib-group><contrib contrib-type="author"><string-name><given-names>J. Keith</given-names> <surname>Pinckard</surname></string-name><x>, </x><degrees>MD PhD</degrees></contrib></contrib-group><pub-date pub-type="epub-ppub"><month>3</month><year>2017</year></pub-date><volume>7</volume><issue>1</issue><issue-title>Themed Issue: The Opioid Crisis</issue-title><fpage>vi</fpage><lpage>vii</lpage><permissions><copyright-statement>© 2017 Academic Forensic Pathology International</copyright-statement><copyright-year>2017</copyright-year><copyright-holder content-type="society">Academic Forensic Pathology International</copyright-holder></permissions><self-uri content-type="pdf" xlink:href="192536211700700101.pdf"/></article-meta></front><body><graphic id="img1-192536211700700101" xlink:href="10.1177_192536211700700101-img1.tif"/><graphic id="img2-192536211700700101" xlink:href="10.1177_192536211700700101-img2.tif"/><p>The theme of the first issue of 2017 is “The Opioid Crisis” and the Special Guest Editor is Dr. Tom Gilson. I believe that “crisis” is an appropriate description of the opioid problem facing the nation. Prescription drug abuse and toxicity have skyrocketed in recent years, especially with the emergence of fentanyl and fentanyl analogs and their introduction into clandestinely produced opioids, including both heroin and other “counterfeit” prescription opioids.</p><p>This crisis, along with the profoundly increased numbers of opioid-related deaths, has affected medicolegal death investigation systems in an unprecedented manner. Offices are becoming overwhelmed with keeping up with the increased numbers of drug-related deaths to the point that they are needing to hire more death investigators and forensic pathologists. Some offices, however, are not sufficiently supported or funded, and thus, the crisis creates a threat to accreditation as well.</p><p>We begin with a pair of articles. The first discusses the need to autopsy all drug-related deaths in order to best serve the public. The second, while acknowledging the desire to function in this way, presents a temporary solution for those who cannot autopsy every potential drug-related death at this time. The next two papers are reviews on the mechanisms of opioid toxicity and of the emerging family of fentanyl analogs. We then feature a paper discussing the evolution of the opioid crisis in one particular jurisdiction. There is also a paper discussing the medicolegal death investigation of potential drug-related deaths. We have a paper describing the public sharing of information involving the medical examiner and another discussing the benefits of prescription drug monitoring programs for medical examiners. There is also a paper discussing particular challenges for coroner systems in the opioid epidemic. Finally, we feature a paper discussing the role of the Burrage decision in criminal proceedings. We also feature several original articles, two of which address issues relevant to the opioid crisis, and two “Case of the Month” papers.</p><p>The second issue of 2017 will be released on June 1; the theme will be “The Death of SIDS” and the Special Guest Editor will be Dr. Melissa Pasquale-Styles. But remember, only about half of each issue is devoted to the specific theme. It's really just a way to promote submission of articles on a particular topic. Manuscripts about any topic can (and should) be submitted at any time! As always, I will continue to encourage the readership to submit articles to the Journal. We depend on submissions from the readership—NAME members like you—to sustain our excellent content.</p></body></article>
